### ISSUE TITLE
Predict result with ckpt file is not good. Do I have to train more?

### ISSUE THREAD

**Issue by drproy2k** [zjjMaiMai/TinyHITNet#1]
Thanks for your great job.
I did predict with your ckpt file which is just downloaded, but the result is not good.
Do I have to train more with SceneFlow or Kitti dataset? or Did I have any mistake?
My script is below,

$ python predict.py --model HITNetXL_SF --ckpt ckpt/hitnet_xl_sf_finalpass_from_tf.ckpt --images test_image/left/000000_10.png test_image/right/000000_10.png --output test_image/est/disp.png

[test_image.zip](https://github.com/zjjMaiMai/TinyHITNet/files/7731173/test_image.zip)

![disp](https://user-images.githubusercontent.com/37288336/146468074-bb03f3b2-eab8-4f15-b703-54d1ef49f8b0.png)

**Comment by zjjMaiMai** [comment]
> Thanks for your great job. I did predict with your ckpt file which is just downloaded, but the result is not good. Do I have to train more with SceneFlow or Kitti dataset? or Did I have any mistake? My script is below,
> 
> $ python predict.py --model HITNetXL_SF --ckpt ckpt/hitnet_xl_sf_finalpass_from_tf.ckpt --images test_image/left/000000_10.png test_image/right/000000_10.png --output test_image/est/disp.png
> 
> [test_image.zip](https://github.com/zjjMaiMai/TinyHITNet/files/7731173/test_image.zip)
> 
> ![disp](https://user-images.githubusercontent.com/37288336/146468074-bb03f3b2-eab8-4f15-b703-54d1ef49f8b0.png)

https://github.com/google-research/google-research/issues/613

**Comment by zjjMaiMai** [comment]
> Thanks for your great job. I did predict with your ckpt file which is just downloaded, but the result is not good. Do I have to train more with SceneFlow or Kitti dataset? or Did I have any mistake?

The hitnet_xl_sf_finalpass_from_tf.ckpt model is trained on sceneflow dataset only, is not expected to work on kitti.
see this thread for more details. google-research/google-research#613 @vtankovich

**Comment by drproy2k** [comment]
Thanks a lot for your quick response.
I've got test with sceneflow data again, the result is great.
Thanks again.
