### ISSUE TITLE
Runtime 

### ISSUE THREAD

**Issue by 4ri4Slr** [zjjMaiMai/TinyHITNet#13]
Hi there,

Thank for the great work. 

Could you verify if this implementation runs in real-time? Do you have a ball park estimate?

Thanks,
Aria

**Comment by zjjMaiMai** [comment]
> Could you verify if this implementation runs in real-time? Do you have a ball park estimate?

I implemented in pure pytorch code, so it won't be as fast as the paper reports, but it should be real-time on GPUs like V100.
