### ISSUE TITLE
can you share your code requirment?

### ISSUE THREAD

**Issue by williamhyin** [zjjMaiMai/TinyHITNet#4]
Hi ,

can you share your code dependency requirement, which could help us alot.
Because i have faced a problem:

  File "train.py", line 9, in <module>
    from metrics.epe import EPEMetric
  File "/workspace/TinyHITNet/metrics/epe.py", line 2, in <module>
    from torchmetrics import AverageMeter
ImportError: cannot import name 'AverageMeter'

even though i have installed pytorch-lightning.

Thanks

**Comment by williamhyin** [comment]
Hi I found the issue:

https://github.com/PyTorchLightning/metrics/releases

Renamed AverageMeter to MeanMetric (#506)

**Comment by zjjMaiMai** [comment]
`pip install torchmetrics`

**Comment by zhangjy328** [comment]
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args', 
ImportError: cannot import name 'DDPPlugin' from 'pytorch_lightning.plugins'，

Hello. Have you successfully completed the training? I encountered a bunch of version issues when running. I'd like to ask which version of pytorch_lightning you are using?
