### ISSUE TITLE
fail to compile ext_op

### ISSUE THREAD

**Issue by Yaoxingtian** [zjjMaiMai/TinyHITNet#5]
> Hi， thanks for you opensource!
when I compile ext_op, error happened:ERROR: Failed building wheel for HitnetModule...

Could you pls. provide env for this project ?

thanks!

**Comment by zjjMaiMai** [comment]
more information please?

**Comment by Yaoxingtian** [comment]
> more information please?
thanks !  I have solved it.
 But another one happened: ModuleNotFoundError: No module named 'dataset
could you pls. help this! 
thanks !'

**Comment by zjjMaiMai** [comment]
>But another one happened: ModuleNotFoundError: No module named 'dataset
could you pls. help this!
thanks !'

you need to add project root dir into PYTHONPATH environment variable.

**Comment by Yaoxingtian** [comment]
> 

Thanks you ! Solved. 
Does this project support two GPUs work ? Could you share the environment you've done? 

new problem again, when I execute  python preprocess/plane_fitting_kitti2015.py :
RuntimeError: CUDA error: invalid device ordinal
thanks so much !

**Comment by zjjMaiMai** [comment]
> new problem again:
RuntimeError: CUDA error: invalid device ordinal
thanks so much !

we hard code 8 GPUs in plane fitting script, you should replace 8 to 2 in your case.
https://github.com/zjjMaiMai/TinyHITNet/blob/6a78b3453bef927f66f04ca3f8949a15509cf3fc/preprocess/plane_fitting_kitti2015.py#L52-L53

**Comment by Yaoxingtian** [comment]
> > new problem again:
> > RuntimeError: CUDA error: invalid device ordinal
> > thanks so much !
> 
> we hard code 8 GPUs in plane fitting script, you should replace 8 to 2 in your case.
> 
> https://github.com/zjjMaiMai/TinyHITNet/blob/6a78b3453bef927f66f04ca3f8949a15509cf3fc/preprocess/plane_fitting_kitti2015.py#L52-L53

Thanks for your help !
And I use two 2080TI , but it shows:RuntimeError: CUDA out of memory.
could you pls. tell me about your training environment?

**Comment by zjjMaiMai** [comment]
> And I use two 2080TI , but it shows:RuntimeError: CUDA out of memory.
could you pls. tell me about your training environment?

we use 8 NVIDIA Tesla V100 GPU 32G.

**Comment by zjjMaiMai** [comment]
try to understand the code and adjust hyperparameters to suit your hardware environment.

**Comment by PMA65** [comment]
> > Hi， thanks for you opensource!
> > when I compile ext_op, error happened:ERROR: Failed building wheel for HitnetModule...
> 
> Could you pls. provide env for this project ?
> 
> thanks!

@Yaoxingtian how did you solve this pls ?

**Comment by Yaoxingtian** [comment]
I just tried diffrent env, and I am not sure the exact proble . my cuda is 11.0.


发送自 Outlook<http://aka.ms/weboutlook>

________________________________
发件人: PMA65 ***@***.***>
发送时间: 2022年2月28日 14:38
收件人: zjjMaiMai/TinyHITNet ***@***.***>
抄送: Yaoxingtian ***@***.***>; Mention ***@***.***>
主题: Re: [zjjMaiMai/TinyHITNet] fail to compile ext_op (Issue #5)


Hi， thanks for you opensource!
when I compile ext_op, error happened:ERROR: Failed building wheel for HitnetModule...

Could you pls. provide env for this project ?

thanks!

@Yaoxingtian<https://github.com/Yaoxingtian> how did you solve this pls ?

―
