### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [zjjMaiMai/TinyHITNet#8]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by zjjMaiMai** [comment]
HITNet-XL model is converted from tensorflow model which is Apache License 2.0.
there is no license for other model, feel free to use it.

**Comment by PINTO0309** [comment]
Thanks! :smile: 

![153523403-afd059d7-6c5b-496e-a418-4b432e2e0f58](https://user-images.githubusercontent.com/33194443/156099599-c83294ed-a5c3-4061-bd28-c70d73317bf5.gif)
